/* tslint:disable */
/* eslint-disable */
/**
 * CIT Student Management Api
 * Manage Students and Their Grades
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface NewStudent {
    'name': string;
    'regNumber': string;
    'gpa': number;
}
export interface Student {
    'id'?: number;
    'name'?: string;
    'regNumber'?: string;
    'gpa'?: number;
}
export interface StudentApiResponse {
    'status'?: string;
    'message'?: string;
    'data'?: Student;
}
export interface StudentListApiResponse {
    'status'?: string;
    'message'?: string;
    'data'?: Array<Student>;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets all students
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StudentsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/students`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Returns a student
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StudentsIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1StudentsIdGet', 'id', id)
            const localVarPath = `/api/v1/students/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Edits an Existing Student
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StudentsIdPut: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiV1StudentsIdPut', 'id', id)
            const localVarPath = `/api/v1/students/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a student
         * @param {NewStudent} newStudent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StudentsPost: async (newStudent: NewStudent, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'newStudent' is not null or undefined
            assertParamExists('apiV1StudentsPost', 'newStudent', newStudent)
            const localVarPath = `/api/v1/students`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(newStudent, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Gets all students
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1StudentsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StudentListApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1StudentsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiV1StudentsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Returns a student
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1StudentsIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StudentApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1StudentsIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiV1StudentsIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Edits an Existing Student
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1StudentsIdPut(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StudentApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1StudentsIdPut(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiV1StudentsIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates a student
         * @param {NewStudent} newStudent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiV1StudentsPost(newStudent: NewStudent, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StudentApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiV1StudentsPost(newStudent, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.apiV1StudentsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Gets all students
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StudentsGet(options?: RawAxiosRequestConfig): AxiosPromise<StudentListApiResponse> {
            return localVarFp.apiV1StudentsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Returns a student
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StudentsIdGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<StudentApiResponse> {
            return localVarFp.apiV1StudentsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Edits an Existing Student
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StudentsIdPut(id: number, options?: RawAxiosRequestConfig): AxiosPromise<StudentApiResponse> {
            return localVarFp.apiV1StudentsIdPut(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a student
         * @param {NewStudent} newStudent 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiV1StudentsPost(newStudent: NewStudent, options?: RawAxiosRequestConfig): AxiosPromise<StudentApiResponse> {
            return localVarFp.apiV1StudentsPost(newStudent, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Gets all students
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1StudentsGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiV1StudentsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Returns a student
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1StudentsIdGet(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiV1StudentsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Edits an Existing Student
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1StudentsIdPut(id: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiV1StudentsIdPut(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates a student
     * @param {NewStudent} newStudent 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiV1StudentsPost(newStudent: NewStudent, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).apiV1StudentsPost(newStudent, options).then((request) => request(this.axios, this.basePath));
    }
}



